name: CI/CD Pipeline Spring Boot

on:
  push:
    branches:
      - main
      - develop
      - nesrine  # Le déploiement Docker se déclenchera sur cette branche
  pull_request:
    branches:
      - main
      - develop
      - nesrine

jobs:
  # Étape 1 : Compilation et Tests
  build:
    name: Build & Test Java
    runs-on: ubuntu-latest

    steps:
      - name: Recuperer le code source
        uses: actions/checkout@v4

      - name: Configurer Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Compiler avec Maven
        run: mvn clean package -DskipTests

      - name: Sauvegarder le fichier JAR
        uses: actions/upload-artifact@v4
        with:
          name: springboot-jar
          path: target/*.jar

  # Étape 2 : Creation et Push de l'image Docker
  docker:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master' # Condition specifique a ta branche

    steps:
      - name: Recuperer le code source
        uses: actions/checkout@v4

      - name: Telecharger le JAR compile
        uses: actions/download-artifact@v4
        with:
          name: springboot-jar
          path: target

      - name: Connexion a Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build et Push de l'image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/springboot-app:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/springboot-app:latest
